# API-Workflow 2.1.0
name: The API Workflow
on: 
  workflow_dispatch:

jobs:
  openapi-diff:
    runs-on: ubuntu-latest
    name: A job which compares tow OAS
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: ODonets/oasDiff-action@master






