# API-Workflow 2.1.0
name: The API Workflow
on: 
  workflow_dispatch:

jobs:
  openapi-diff:
    runs-on: ubuntu-latest
    name: A job which compares tow OAS
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: ODonets/oasDiff-action@main

      - name: Upload change log
        uses: actions/upload-artifact@v2
        env:
          CHANGE_LOG_ARTIFACT_NAME: change-log
          CHANGE_LOG_ARTIFACT_FILENAME: changeLog.md
        with:
          name: ${{ env.CHANGE_LOG_ARTIFACT_NAME }}
          path: ${{ env.CHANGE_LOG_ARTIFACT_FILENAME }}
